### ISSUE TITLE
请问为什么跑demo出来的bounding box 是乱的

### ISSUE THREAD

**Issue by zzdang** [MhLiao/RRD#2]
您好,跑demo出来的bounding box 是乱的,是哪里出问题了,你那边确定可以跑出来结果吗

**Comment by northeastsquare** [comment]
![image](https://user-images.githubusercontent.com/3086078/42456076-7eea4982-83c6-11e8-8736-104810b89bac.png)

**Comment by northeastsquare** [comment]
I also met this

**Comment by MhLiao** [comment]
That's strange. I will check it.

**Comment by MhLiao** [comment]
Do you use GPU mode or CPU mode? There is a bug in the CPU code. I have fixed the bug in CPU code now.

**Comment by zzdang** [comment]
解决了,是我这边caffe路径没给对
